Add blobstorage service
maxXximus23/AchieveIt pull request #7
Opened 2022-01-26 21:44 UTC by maxXximus23

- Add azure blob storage packet;
- Set up appsettings and Startup for azure blob storage;
- Add Blob storage Service.

2022-01-26 21:49 UTC, kirpichyov commented
Please verify your changes...

2022-01-26 22:01 UTC, kirpichyov requested changes

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.API/Controllers/AuthController.cs
> +        public AuthController(IAuthService authService, IMapper mapper, IBlobService blobService)
Please remove. Looks like added unintentionally.

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            throw new System.NotImplementedException();
Please remove this method (from the contract as well).

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.API/Program.cs
> -                .AddJsonFile("appsettings.json")
Looks like that will lead to the problems with logging

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            var containerClient = _blobServiceClient.GetBlobContainerClient("avatars");
Looks like should be moved to parameter

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            var container = _blobServiceClient.GetBlobContainerClient("avatars");
Looks like should be moved to parameter

2022-01-26 22:01 UTC, kirpichyov commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +                ContentDisposition = $"{(inline? "inline" : "attachment")}; filename=\"{file.FileName}\";"
Suggestion for formatting:
`inline ?`

2022-01-26 22:12 UTC, maxXximus23 commented on AchieveIt.API/Controllers/AuthController.cs
> +        public AuthController(IAuthService authService, IMapper mapper, IBlobService blobService)
Done.

2022-01-26 22:14 UTC, maxXximus23 commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            throw new System.NotImplementedException();
Done.

2022-01-26 22:14 UTC, maxXximus23 commented on AchieveIt.API/Program.cs
> -                .AddJsonFile("appsettings.json")
Done.

2022-01-26 22:17 UTC, maxXximus23 commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            var containerClient = _blobServiceClient.GetBlobContainerClient("avatars");
Done.

2022-01-26 22:17 UTC, maxXximus23 commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +            var container = _blobServiceClient.GetBlobContainerClient("avatars");
Done.

2022-01-26 22:17 UTC, maxXximus23 commented on AchieveIt.BusinessLogic/Services/BlobService.cs
> +                ContentDisposition = $"{(inline? "inline" : "attachment")}; filename=\"{file.FileName}\";"
Done.

2022-01-26 22:25 UTC, kirpichyov approved these changes

2022-01-27 14:16 UTC, qrilo approved these changes

2022-01-27 14:23 UTC, merged